version:   "3.9"

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
    secrets:
      - db_root_password
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - mongodb_network
    ports:
      - 37017:27017
      - 9229:9229
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:37017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD_FILE=/run/secrets/db_root_password
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD_FILE=/run/secrets/me_admin_password
    secrets:
      - db_root_password
      - me_admin_password
    volumes:
      - mongodb-data
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - 9081:8081

secrets:
  db_root_password:
    file: db_root_password.txt
  me_admin_password:
    file: me_admin_password.txt
   
volumes:
  mongodb-data:
    name: mongodb-data

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge